version: "3"
services:
  redis:
    image: "redis:alpine"
    deploy:
      placement:
        constraints: [node.role == manager]
    expose:
      - 6379
    networks:
      - webnet
  db:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: thesis
    volumes: 
      - db-data:/var/lib/postgresql/data
    # It actually need to be on the same fucking network:
    networks:
      - webnet
  web:
    build: .
    # image: tutora
    # deploy:
    #   replicas: 5
    #   restart_policy:
    #     condition: on-failure
    #   resources:
    #     limits:
    #       cpus: "0.1"
    #       memory: 50M
    links:
      - db
    ports:
      - "80:3000"
    networks:
     - webnet
    # volumes:
    #  - .:/usr/src/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - COMPOSE_PROJECT_NAME=tutora
      - DOCKER=isTrue
    networks:
      - webnet
volumes:
  db-data:
networks:
  webnet: