version: "3"
services:
  web:
    image: tomdickson/tutora
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
      #ports:
       # - "3000:3000"
      #networks:
       # - webnet
  redis:
    image: redis
    ports:
      - "6739:6739"
    volumes:
      - ./data:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet: