version: "3"
services:
  web:
    image: tutora
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "3000:3000"
    networks:
     - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    #volumes:
     # - ./data:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet: